export const SET_TITLE_SUCCESS = 'app/SET_TITLE_SUCCESS'
export const VIDEOS_SINGLE_LOADED = 'app/VIDEOS_SINGLE_LOADED'

export const LOAD_YOUTUBE_VIDEO_DETAILS = 'app/LOAD_YOUTUBE_VIDEO_DETAILS'
export const LOAD_YOUTUBE_VIDEO_DETAILS_SUCCESS = 'app/LOAD_YOUTUBE_VIDEO_DETAILS_SUCCESS'
